name: Check Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-executables:
    runs-on: ubuntu-latest

    env:
      EXECUTABLES: "my_torch_generator my_torch_analyzer"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if files are executable
        shell: bash
        run: |
              IFS=' '
              readarray -t files <<<"${{ env.EXECUTABLES }}"
              return_value=0

              make

              for file in "${files[@]}"
              do
                if [ -x "$file" ]
                then
                  echo "::notice title="Executable file test", file=$file:: The file $file is an executable"
                else
                  echo "::error title="Executable file test", file=$file:: The file $file is not an executable or does not exist"
                  return_value=1
                fi
              done
              exit $return_value